# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 152750039+code-alexander@users.noreply.github.com
author_name: code-alexander
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: py2algo

